source 'https://github.com/CocoaPods/Specs.git'

workspace 'FriendFinder.xcworkspace' # Your project's workspace
project 'FriendFinder.xcodeproj' # Your project's Xcode project
project 'Frameworks/External/PXGoogleDirections/PXGoogleDirections.xcodeproj' # Update folder structure if needed

target 'FriendFinder' do

  project 'FriendFinder.xcodeproj'
  platform :ios, '10.0'
  use_frameworks!
  
  # Pods for FriendFinder

  #Database
  pod 'Firebase/Core'

  #Map
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  #Authentication libraries

  #pod 'FirebaseUI/Twitter'

  pod 'FirebaseUI/Phone'

  # Only pull in FirebaseUI Auth features
  pod 'FirebaseUI/Auth', '~> 4.0'

  # Only pull in Facebook login features
  pod 'FirebaseUI/Facebook', '~> 4.0'

  #Facebook
  pod 'FacebookLogin'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'  
  pod 'FBSDKLoginKit' 

  # Only pull in Google login features
  pod 'FirebaseUI/Google', '~> 4.0'

  # Only pull in database
  pod 'Firebase/Database'

  # Only pull in storage
  pod 'Firebase/Storage'

  # For icons
  pod 'FontAwesome.swift'
  
  # For session semantics
  pod 'PubNub', '~>4.6'

  # For slide view
  pod 'SideMenu'

  # For expandable cell
  pod 'ExpandableCell'

  target 'FriendFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# This tells Cocoapods how to build the subproject
target 'PXGoogleDirections' do
   project 'Frameworks/External/PXGoogleDirections/PXGoogleDirections.xcodeproj'
   platform :ios, '8.1'
   inherit! :search_paths
 
end
