# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FriendFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for FriendFinder
  pod 'Firebase/Core'

  #Authentication libraries
  pod 'FirebaseUI/Auth' 
  #pod 'FirebaseUI/Google'
  #pod 'FirebaseUI/Facebook'
  #pod 'FirebaseUI/Twitter'
  #pod 'FirebaseUI/Phone'



  target 'FriendFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
